### ISSUE TITLE
Basic try  - The requested module 'casbin' does not provide an export named 'newEnforcer' 

### ISSUE THREAD

**Issue by ronycohen** [casbin/node-casbin#201]
Hi, 
I'm just trying your lib, but I probably miss something.
I get an error like : SyntaxError: The requested module 'casbin' does not provide an export named 'newEnforcer'

node -v
v12.16.1
npm -v
6.13.4

**PACKAGE .JSON** 

```json
{
  "name": "acl",
  "version": "1.0.0",
  "description": "",
  "main": "casbin.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node --experimental-modules index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "casbin": "^5.1.6"
  }
}
```

**INDEX.JS**

```js
import { newEnforcer } from 'casbin';

async function launch() {
    const e = await newEnforcer('model.conf', 'policy.csv');

    const sub = 'alice'; // the user that wants to access a resource.
    const obj = 'data1'; // the resource that is going to be accessed.
    const act = 'read'; // the operation that the user performs on the resource.

    if ((await e.enforce(sub, obj, act)) === true) {
        // permit alice to read data1
        let roles = await e.getRolesForUser('alice');
        console.log(roles);

    } else {
        // deny the request, show an error
    }
}

launch();
```

ERROR  : 

```cmd
npm run start

> acl@1.0.0 start /path
> node --experimental-modules index.js

(node:15656) ExperimentalWarning: The ESM module loader is experimental.
file:///path/index.js:1
import { newEnforcer } from 'casbin';
         ^^^^^^^^^^^
SyntaxError: The requested module 'casbin' does not provide an export named 'newEnforcer'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:164:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! acl@1.0.0 start: `node --experimental-modules index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the acl@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by hsluoyz** [comment]
@nodece @zhmushan

**Comment by nodece** [comment]
@ronycohen  `import casbin from 'casbin';` is working.
