### ISSUE TITLE
Can not add role for a user in case g = _, _, _

### ISSUE THREAD

**Issue by ghaiklor** [casbin/node-casbin#25]
I have the following role definition:

```ini
[role_definition]
g = _, _, _
```

But, when I am trying to add a role for a user, the function `addRoleForUser` accepts only two parameters (it is hardcoded), so I can not provide the domain.

Here is the test-case I wrote to check that:

```typescript
    it('Should properly add new role to user and remove it from the enforcer', async () => {
        const enforcer = await getEnforcer();

        assert.deepEqual(await enforcer.getGroupingPolicy(), []);
        // here I am trying to add role, but signature for the method accepts only user and role
        assert.isTrue(await enforcer.addRoleForUser('subject', 'role', 'domain'));
    });

```

So, as a result, I am getting the following error:

```
Error: grouping policy elements do not meet role definition
      at Assertion.buildRoleLinks (node_modules/casbin/lib/model/assertion.js:40:23)
      at astMap.forEach.value (node_modules/casbin/lib/model/model.js:123:19)
      at Map.forEach (<anonymous>)
      at Model.buildRoleLinks (node_modules/casbin/lib/model/model.js:122:16)
      at Enforcer.buildRoleLinks (node_modules/casbin/lib/coreEnforcer.js:246:20)
      at Enforcer.<anonymous> (node_modules/casbin/lib/managementEnforcer.js:339:22)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/casbin/lib/managementEnforcer.js:17:58)
```

**Comment by ghaiklor** [comment]
I am wondering if the same inconsistency in similar methods like `getUsersForRole`...

**Comment by hsluoyz** [comment]
Hi. The ``domain`` param has been added, see: https://github.com/casbin/node-casbin/commit/e876217bcf4e352fc73bd98949c74812661c0e47

**Comment by ghaiklor** [comment]
Yeah, the first one with removing grouping policies seems like resolved. My test case was able to resolve.

Just to note the test case I'm talking about:

```javascript
        assert.isFalse(await enforcer.hasGroupingPolicy('subject', 'role', 'scope'));
        assert.isTrue(await enforcer.addGroupingPolicy('subject', 'role', 'scope'));
        assert.isTrue(await enforcer.hasGroupingPolicy('subject', 'role', 'scope'));
        assert.isTrue(await enforcer.removeGroupingPolicy('subject', 'role', 'scope'));
        assert.isFalse(await enforcer.hasGroupingPolicy('subject', 'role', 'scope'));
```

**Comment by hsluoyz** [comment]
Can you check this issue too?

**Comment by ghaiklor** [comment]
sure, let me build casbin locally then with your last changes, few minutes...

**Comment by ghaiklor** [comment]
At first glance it works fine. Here is my test cases for roles:

```javascript
    // https://github.com/casbin/node-casbin/issues/24
    it('Should properly add new grouping policy and remove it from the enforcer', async () => {
        const enforcer = await getEnforcer();

        assert.isFalse(await enforcer.hasGroupingPolicy('subject', 'role', 'scope'));
        assert.isTrue(await enforcer.addGroupingPolicy('subject', 'role', 'scope'));
        assert.isTrue(await enforcer.hasGroupingPolicy('subject', 'role', 'scope'));
        assert.isTrue(await enforcer.removeGroupingPolicy('subject', 'role', 'scope'));
        assert.isFalse(await enforcer.hasGroupingPolicy('subject', 'role', 'scope'));
    });

    // https://github.com/casbin/node-casbin/issues/25
    it('Should properly add new role to user and remove it from the enforcer', async () => {
        const enforcer = await getEnforcer();

        assert.deepEqual(await enforcer.getGroupingPolicy(), []);
        assert.isTrue(await enforcer.addRoleForUser('ghaiklor', 'guest', 'elastic'));
        assert.deepEqual(await enforcer.getGroupingPolicy(), [['ghaiklor', 'guest', 'elastic']]);
        assert.isTrue(await enforcer.hasGroupingPolicy('ghaiklor', 'guest', 'elastic'));
        assert.isTrue(await enforcer.deleteRoleForUser('ghaiklor', 'guest', 'elastic'));
        assert.deepEqual(await enforcer.getGroupingPolicy(), []);
    });
```

**Comment by hsluoyz** [comment]
I think this is enough :) I have released ``1.1.4`` here: https://www.npmjs.com/package/casbin/v/1.1.4

**Comment by ghaiklor** [comment]
I just finished with covering all the remaining methods with similar tests and everything is ok. Though, I've found the last one issue with `getUsersForRole`.

Here is the test case:

```javascript
// add the roles
assert.isTrue(await enforcer.addRoleForUser('ghaiklor', 'admin', 'tenant A'));
assert.isTrue(await enforcer.addRoleForUser('ghaiklor', 'guest', 'tenant B'));

// check if roles are assigned
assert.deepEqual(await enforcer.getRolesForUser('ghaiklor', 'tenant A'), ['admin']);
assert.deepEqual(await enforcer.getRolesForUser('ghaiklor', 'tenant B'), ['guest']);

// but these are failing
assert.deepEqual(await enforcer.getUsersForRole('admin', 'tenant A'), ['ghaiklor']);
assert.deepEqual(await enforcer.getUsersForRole('admin', 'tenant B'), []);
assert.deepEqual(await enforcer.getUsersForRole('guest', 'tenant A'), []);
assert.deepEqual(await enforcer.getUsersForRole('guest', 'tenant B'), ['ghaiklor']);

// though, these are working just fine
assert.isTrue(await enforcer.hasRoleForUser('ghaiklor', 'admin', 'tenant A'));
assert.isTrue(await enforcer.hasRoleForUser('ghaiklor', 'guest', 'tenant B'));
assert.isFalse(await enforcer.hasRoleForUser('ghaiklor', 'admin', 'tenant B'));
assert.isFalse(await enforcer.hasRoleForUser('ghaiklor', 'guest', 'tenant A'));
```

`getUsersForRole` are failing with the error:

```
 Error: error: name does not exist
      at DefaultRoleManager.getUsers (/Users/ghaiklor/Library/Projects/node-casbin/lib/rbac/defaultRoleManager.js:98:19)
      at Enforcer.getUsersForRole (/Users/ghaiklor/Library/Projects/node-casbin/lib/enforcer.js:169:23)
      at Context.it (spec-mocha/unit/casbin.spec.js:94:41)
```

**Comment by hsluoyz** [comment]
What you found is another bug. It should have been fixed in: https://github.com/casbin/node-casbin/commit/bf656cc20a7b78b6c38882ec905dfbdd0e3c70c3

**Comment by ghaiklor** [comment]
Is there a possibility to not include domain as a prefix ?

IMO, it is more UX-friendly when `getUsersForRole` returns only a subject as it specified in grouping policy, without domain prefix. Though, if it is hard to do in terms of casbin, it's fine.

**Comment by hsluoyz** [comment]
It has been fixed in: https://github.com/casbin/node-casbin/commit/cbc1a782a3bc34e8a4acc3f3a502d5124e7dfc78

**Comment by ghaiklor** [comment]
I've finished covering few more edge cases for management api and everything is passing with your latest `master` branch.

So, you can publish new version from the `master`. To be clear, I've covered all the interfaces in Enforcer, so seems like ALL of it working as expected in terms of `g = _, _, _`.

**Comment by hsluoyz** [comment]
Good to hear it. I have released ``1.1.5``: https://www.npmjs.com/package/casbin/v/1.1.5

BTW, if you have time, you can add your tests to this project's [test](https://github.com/casbin/node-casbin/tree/master/test) :)

**Comment by ghaiklor** [comment]
I've written them in JavaScript, not TypeScript, so I'm not sure it fits it :)

**Comment by hsluoyz** [comment]
OK It's a pity :(
