### ISSUE TITLE
TypeError: rvals[j].trim is not a function

### ISSUE THREAD

**Issue by ahushh** [casbin/node-casbin#27]
Get that error trying to use both of ABAC and RBAC models.

I have the following model:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act) || r.sub.id == r.obj.owner
```

Also some records in 'policy.csv' which look like:

```csv
p, admin, post, delete
```

Here is my code:

```js
enforcer.enforce('admin', 'post', 'delete') // works fine.
```

```js
enforcer.enforce({ id: 1 }, { name: 'post', owner: 1 }, act) // is failing with the error:
```

```shell
(node:77674) UnhandledPromiseRejectionWarning: TypeError: rvals[j].trim is not a function
    at model.model.get.get.tokens.forEach (/Users/ahushh/Projects/casbin/node_modules/casbin/lib/coreEnforcer.js:291:54)
    at Array.forEach (<anonymous>)
    at Enforcer.enforce (/Users/ahushh/Projects/casbin/node_modules/casbin/lib/coreEnforcer.js:290:59)
    at Object.<anonymous> (/Users/ahushh/Projects/casbin/index.ts:13:14)
    at step (/Users/ahushh/Projects/casbin/index.ts:32:23)
    at Object.next (/Users/ahushh/Projects/casbin/index.ts:13:53)
    at fulfilled (/Users/ahushh/Projects/casbin/index.ts:4:58)
(node:77674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:77674) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've tried to fix that by removing trim call when `rvals[j]` is not a string and it works. But this is my first use of Casbin and I'm not sure if I use Casbin correctly at all.

Versions:

```json
  "dependencies": {
    "@types/node": "^10.12.3",
    "casbin": "^1.1.5",
    "ts-node": "^7.0.1",
    "typescript": "^3.1.6"
  }
```

**Comment by hsluoyz** [comment]
This error is because your ``r.sub`` is a struct: ``{ id: 1 }`` in ``g(r.sub, p.sub)``. The ``g`` function only accepts two string parameters, to check whether the 1st param ``r.sub`` has a role named the 2nd param ``p.sub``.

``enforcer.enforce('admin', 'post', 'delete')`` works because the first half of matcher: ``(g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act)`` is true, so Casbin doesn't check the second half: ``r.sub.id == r.obj.owner``. If it checks, you will also get error, as there's no ``.id`` or ``.owner`` for strings.

As a fix, you'd better make ``r.sub`` and ``r.obj`` be always structs, instead of sometimes string, sometimes struct, which make things complicated. For example, use a matcher like:

```ini
[matchers]
m = (g(r.sub.name, p.sub) && r.obj.name == p.obj && r.act == p.act) || r.sub.id == r.obj.owner
```

Then check the permission with:

```js
enforcer.enforce({ id: 0, name: 'admin' }, { name: 'post', owner: 99999}, 'delete')

enforcer.enforce({ id: 1, name: 'alice' }, { name: 'post', owner: 1 }, act)
```

**Comment by ahushh** [comment]
Thanks for your explanation.
