### ISSUE TITLE
keyGet2 always returns *matcher result should be boolean or number*

### ISSUE THREAD

**Issue by tomfriedhof** [casbin/node-casbin#332]
I have confirmed that the operator does in fact return the correct value. However, it is not making back from the `coreEnforcer`. This is what my stack trace looks like when running this:

```
      matcher result should be boolean or number

      at Enforcer.privateEnforce (/app/node_modules/casbin/lib/cjs/coreEnforcer.js:391:31)
      at privateEnforce.next (<anonymous>)
      at Object.generatorRunAsync (/app/node_modules/casbin/lib/cjs/util/util.js:154:41)
      at async testEnforce (/app/test/casbin/user.test.ts:34:20)
      at async /app/test/casbin/user.test.ts:25:9
```

I am running enforce with the following params:

```
const params = {
        sub: "role::sales",
        input: { sub, obj },
        obj: '/user/123',
        act: "ListUsers",
      };
await e.enforce(params.input, params.sub, params.obj, params.act);
```

Here is what the matcher looks like:

```
[matchers]
m = g(r.sub, p.sub) && keyGet2(r.obj, p.obj, 'role')
```

and policy:

```
p, /user/:role, role::sales, ListUsers
```

**Comment by hsluoyz** [comment]
Hi @tomfriedhof sorry for late response. Can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@foxzero-007

**Comment by hsluoyz** [comment]
@fabian4

**Comment by hsluoyz** [comment]
@Shivansh-yadav13

**Comment by Shivansh-yadav13** [comment]
isn't the request size max 3 for enforcer? that would give an error or I'm missing something here??

**Comment by Shivansh-yadav13** [comment]
when using keyGet2 the type of result in enforcer is undefined due to which it is throwing this error.

**Comment by Shivansh-yadav13** [comment]
const result = asyncCompile ? yield expression(context) : expression(context); is returning undefined.

**Comment by nodece** [comment]
You pass incorrect params to enforce:
```
const params = {
        sub: "role::sales",
        input: { sub, obj },
        obj: '/user/123',
        act: "ListUsers",
      };
await e.enforce(params.input.sub, params.input.obj, params.sub, params.obj, params.act);
```
