### ISSUE TITLE
Enforce auth problem

### ISSUE THREAD

**Issue by bobpaul2612** [casbin/node-casbin#47]
hi every one

i have a new problem when i try the simple example

i write a simple function named casbin_test() , and "keymatch_model.conf" , "keymatch_policy.csv"
is the example files.

but the 
```js
enforcer.enforce(sub, obj, act)
```
is always return "false"

```js
async function casbin_test() {
    const enforcer = await casbin.newEnforcer('./keymatch_model.conf', './keymatch_policy.csv');
    const sub = 'alice'; // the user that wants to access a resource.
    const obj = '/alice_data/'; // the resource that is going to be accessed.
    const act = 'GET'; // the operation that the user performs on the resource.

    if (enforcer.enforce(sub, obj, act) == true) {
        console.log('permit alice to read data1');
    } else {
        console.log('deny the request, show an error');
    }
}
```

and when i want check the roles that a user has
```js
    async function casbin_test() {
    const enforcer = await casbin.newEnforcer('./keymatch_model.conf', './keymatch_policy.csv');
    console.log(enforcer.getRolesForUser('alice'));
}
```

it will display
```
0|CIA  | 2019-01-30 10:07 +08:00: TypeError: Cannot read property 'get' of undefined
0|CIA  | 2019-01-30 10:07 +08:00:     at Enforcer.getRolesForUser (/home/node_modules/casbin/lib/enforcer.js:84:45)
0|CIA  | 2019-01-30 10:07 +08:00:     at casbin_test (/home/app.js:93:26)
```

**Comment by nodece** [comment]
1. Please provide policy about always return false
2. Call `getPermissionsForUser` get permissions that a user has  in ACL model

**Comment by bobpaul2612** [comment]
this is my model
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```
and this one is my policy
```
p,alice,/alice_data/*,GET
p,alice,/alice_data/resource1,POST
p,bob,/alice_data/resource2,GET
p,bob,/bob_data/*,POST
p,cathy,/cathy_data,(GET)|(POST)
```
i write a test function
```js
async function casbin_test() {
    const enforcer = await casbin.newEnforcer('./keymatch_model.conf', './keymatch_policy.csv');
    const sub = 'alice'; // the user that wants to access a resource.
    const obj = '/alice_data/'; // the resource that is going to be accessed.
    const act = 'GET'; // the operation that the user performs on the resource.

    console.log(enforcer);

    console.log('the user permission is : ' + enforcer.getPermissionsForUser('alice'));

    if (enforcer.enforce(sub, obj, act) == true) {
        console.log('permit alice to read data1');
    } else {
        console.log('deny the request, show an error');
    }
}
```

and the result is
```
0|CIA  | 2019-01-30 13:53 +08:00: Enforcer {
0|CIA  | 2019-01-30 13:53 +08:00:   adapter: FileAdapter { filePath: './keymatch_policy.csv' },
0|CIA  | 2019-01-30 13:53 +08:00:   watcher: null,
0|CIA  | 2019-01-30 13:53 +08:00:   model:
0|CIA  | 2019-01-30 13:53 +08:00:    Model {
0|CIA  | 2019-01-30 13:53 +08:00:      model:
0|CIA  | 2019-01-30 13:53 +08:00:       Map { 'r' => [Map], 'p' => [Map], 'e' => [Map], 'm' => [Map] } },
0|CIA  | 2019-01-30 13:53 +08:00:   fm:
0|CIA  | 2019-01-30 13:53 +08:00:    FunctionMap {
0|CIA  | 2019-01-30 13:53 +08:00:      functions:
0|CIA  | 2019-01-30 13:53 +08:00:       Map {
0|CIA  | 2019-01-30 13:53 +08:00:         'keyMatch' => [Function: keyMatchFunc],
0|CIA  | 2019-01-30 13:53 +08:00:         'keyMatch2' => [Function: keyMatch2Func],
0|CIA  | 2019-01-30 13:53 +08:00:         'regexMatch' => [Function: regexMatchFunc],
0|CIA  | 2019-01-30 13:53 +08:00:         'ipMatch' => [Function: ipMatchFunc] } },
0|CIA  | 2019-01-30 13:53 +08:00:   rm:
0|CIA  | 2019-01-30 13:53 +08:00:    DefaultRoleManager { allRoles: Map {}, maxHierarchyLevel: 10 },
0|CIA  | 2019-01-30 13:53 +08:00:   eft: DefaultEffector {},
0|CIA  | 2019-01-30 13:53 +08:00:   enabled: true,
0|CIA  | 2019-01-30 13:53 +08:00:   autoSave: true,
0|CIA  | 2019-01-30 13:53 +08:00:   autoBuildRoleLinks: true,
0|CIA  | 2019-01-30 13:53 +08:00:   modelPath: './keymatch_model.conf' }
0|CIA  | 2019-01-30 13:53 +08:00: the user permission is : 
0|CIA  | 2019-01-30 13:53 +08:00: deny the request, show an error
```
i think that it can`t load the policy correct.

had method can show load policy?

**Comment by bobpaul2612** [comment]
i found that because i didn`t have a space , the program was wrong.

now i slaved this problem

thank for reply
