### ISSUE TITLE
Throws ERROR Unexpected token import

### ISSUE THREAD

**Issue by HarshadMohape0904** [casbin/node-casbin#89]
Hi,
I am trying the example given in node-casbin readme and facing following error.

error: uncaughtException: Unexpected token import
/server/services/casbin.service.js:1
(function (exports, require, module, __filename, __dirname) { import * as casbin from 'casbin';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/server/routers/casbin.routes.js:3:21)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/server/routers/app.routes.js:95:24)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

**Comment by nodece** [comment]
@HarshadMohape0904 Using `const casbin = require('casbin');` instead of `import * as casbin from 'casbin';`

**Comment by hsluoyz** [comment]
@HarshadMohape0904  why were you using Casbin in wrong way? Do we have incorrect docs? If yes, please report it. We will fix it.

**Comment by HarshadMohape0904** [comment]
I tried the above solution but it leads me to a new error as below. 

var test = await casbin.newEnforcer("../path/model.conf", "../path/policy.csv").then(function (enforcer) {
                         ^^^^^^

SyntaxError: Unexpected identifier
   at createScript (vm.js:80:10)
   at Object.runInThisContext (vm.js:139:10)
   at Module._compile (module.js:607:28)
   at Object.Module._extensions..js (module.js:654:10)
   at Module.load (module.js:556:32)
   at tryModuleLoad (module.js:499:12)
   at Function.Module._load (module.js:491:3)
   at Function.Module.runMain (module.js:684:10)
   at startup (bootstrap_node.js:187:16)
   at bootstrap_node.js:608:3

**Comment by akshay27395** [comment]
@HarshadMohape0904 The await method is not working. please use

**Comment by HarshadMohape0904** [comment]
> @HarshadMohape0904 The await method is not working.
> Please use the following function.
> 
> ```
> casbin.newEnforcer("../path/model.conf", "../path/policy.csv").then(function (enforcer) {
>           console.log("success =  ", enforcer)
> }).catch(function (error) {
>             console.log("error =  ", error)
> })
> ```

Thanks, @akshay27395 I tried it and it worked...!
